# Generated by Django 5.2.1 on 2025-05-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nic',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='NIC Number'),
        ),
    ]
